# Generated by Django 4.1.5 on 2023-01-18 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("token_type", models.CharField(max_length=128)),
                ("access_token", models.CharField(max_length=5140)),
                ("refresh_token", models.CharField(max_length=128)),
                ("expires_at", models.PositiveIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alliance_id", models.PositiveIntegerField(null=True)),
                ("birthday", models.DateTimeField(null=True)),
                ("bloodline_id", models.PositiveIntegerField(null=True)),
                ("corporation_id", models.PositiveIntegerField(null=True)),
                ("description", models.TextField(max_length=8192, null=True)),
                ("gender", models.CharField(max_length=16, null=True)),
                ("race_id", models.PositiveIntegerField(null=True)),
                ("security_status", models.FloatField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
